image: docker:19.03.1
variables:
  #GIT_SUBMODULE_STRATEGY: recursive
  COUCHDB_USER: op
  COUCHDB_PASSWORD: op
  #GIT_STRATEGY: none


# services:
#   - docker:19.03.1-dind

stages:
  - build
  - test

build:
  stage: build
  before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.quintagroup.com:443
  script:
    - docker build -t registry.gitlab.quintagroup.com:443/pricequotation/openprocurement.api:$CI_COMMIT_REF_NAME .
    - docker push registry.gitlab.quintagroup.com:443/pricequotation/openprocurement.api:$CI_COMMIT_REF_NAME
  tags:
    - dind
  only:
    - quinta
    - merge_requests


#trigger_deploy:
#  image: curlimages/curl
#  stage: deploy
#  tags:
#    - dind
#  script:
#    - "curl -X POST -F token=$RUN_TOKEN -F ref=$CI_COMMIT_REF_NAME https://gitlab.quintagroup.com/api/v4/projects/1204/trigger/pipeline"
#  only:
#    - quinta
#  when: manual


.setuptools:
  image: python:2.7
  stage: test
  services:
    - couchdb:1.7.2
  tags:
    - dind
  variables:
    GIT_STRATEGY: clone
  only:
    - branches
  except:
    - schedules
  before_script:
    - apt-get update
    - apt-get install -y libsodium-dev
    - pip install --upgrade pip setuptools

test:
  extends: .setuptools
  script:
    - python setup.py test
  when: manual


.test:
  image: registry.gitlab.quintagroup.com:443/pricequotation/openprocurement.api:$CI_COMMIT_REF_NAME
  stage: test
  services:
    - couchdb:1.7.2
  tags:
    - dind
  only:
    - quinta
    - merge_requests
  dependencies:
    - build
  script:
    - cd /app
    - py.test $TESTS_PATH --cov=$COV_PATH --cov-config=$COV_FILE -v --color=yes --dist=each
      --tx=popen//id=sand//env:DB_NAME=test_sandbox//env:SANDBOX_MODE=1//env:SINGLE_APP=1
      --tx=popen//id=prod//env:DB_NAME=test_prod//env:SANDBOX_MODE=//env:SINGLE_APP=1
      --tx=popen//id=sand_relsease_2020_04_19//env:DB_NAME=test_sandbox_2020_04_19//env:SANDBOX_MODE=1//env:SINGLE_APP=1//env:DEFAULT_RELEASE_2020_04_19=2020-01-01
      --tx=popen//id=prod_relsease_2020_04_19//env:DB_NAME=test_prod_2020_04_19//env:SANDBOX_MODE=//env:SINGLE_APP=1//env:DEFAULT_RELEASE_2020_04_19=2020-01-01
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'

test_relocation_api:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/relocation/api/tests
    COV_PATH: src/openprocurement/relocation/api
    COV_FILE: .coveragerc

test_tender_esco:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/tender/esco/tests
    COV_PATH: src/openprocurement/tender/esco
    COV_FILE: .coveragerc

test_tender_openeu:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/tender/openeu/tests
    COV_PATH: src/openprocurement/tender/openeu
    COV_FILE: .coveragerc

test_tender_cfaua:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/tender/cfaua/tests
    COV_PATH: src/openprocurement/tender/cfaua
    COV_FILE: .coveragerc

test_tender_comp_stage2:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/tender/competitivedialogue/tests/stage2
    COV_PATH: src/openprocurement/tender/competitivedialogue/
    COV_FILE: src/openprocurement/tender/competitivedialogue/tests/stage2/.coveragerc

test_tender_core:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/tender/core/tests
    COV_PATH: src/openprocurement/tender/core
    COV_FILE: .coveragerc

test_api:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/api/tests
    COV_PATH: src/openprocurement/api
    COV_FILE: .coveragerc

test_agreement_core:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/agreement/core/tests
    COV_PATH: src/openprocurement/agreement/core
    COV_FILE: .coveragerc

test_agreement_cfaua:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/agreement/cfaua/tests
    COV_PATH: src/openprocurement/agreement/cfaua
    COV_FILE: .coveragerc

test_contracting_api:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/contracting/api/tests
    COV_PATH: src/openprocurement/contracting/api
    COV_FILE: .coveragerc

test_planning_api:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/planning/api/tests
    COV_PATH: src/openprocurement/planning/api
    COV_FILE: .coveragerc

test_historical_core:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/historical/core/tests
    COV_PATH: src/openprocurement/historical/core
    COV_FILE: .coveragerc

test_historical_tender:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/historical/tender/tests
    COV_PATH: src/openprocurement/historical/tender
    COV_FILE: .coveragerc

test_tender_comp_stage1:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/tender/competitivedialogue/tests/stage1
    COV_PATH: src/openprocurement/tender/competitivedialogue/
    COV_FILE: src/openprocurement/tender/competitivedialogue/tests/stage1/.coveragerc

test_tender_limited:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/tender/limited/tests
    COV_PATH: src/openprocurement/tender/limited
    COV_FILE: .coveragerc

test_tender_openua:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/tender/openua/tests
    COV_PATH: src/openprocurement/tender/openua
    COV_FILE: .coveragerc

test_tender_belowthreshold:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/tender/belowthreshold/tests
    COV_PATH: src/openprocurement/tender/belowthreshold
    COV_FILE: .coveragerc

test_tender_openuadefense:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/tender/openuadefense/tests
    COV_PATH: src/openprocurement/tender/openuadefense
    COV_FILE: .coveragerc

test_tender_cfaselectionua:
  extends: .test
  variables:
    TESTS_PATH: src/openprocurement/tender/cfaselectionua/tests
    COV_PATH: src/openprocurement/tender/cfaselectionua
    COV_FILE: .coveragerc


